# Generated by Django 5.2.15 on 2026-06-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_alter_cart_user"),
        ("products", "0006_product_quantity"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                fields=("cart", "product"), name="unique_product_in_cart"
            ),
        ),
    ]
