# Generated by Django 5.2.15 on 2026-06-17 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_alter_cartitem_quantity"),
        ("orders", "0002_order_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="cart.cart",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="country",
            field=models.CharField(default="United States", max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(max_length=100),
        ),
    ]
