# Generated by Django 5.2.15 on 2026-06-18 13:36

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_cart_order_country_alter_order_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="country",
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name="order",
            name="zipcode",
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
