# Generated by Django 5.2.15 on 2026-07-09 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_alter_order_coupon_alter_order_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="is_paid",
        ),
    ]
