# Generated by Django 5.2.15 on 2026-07-10 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_cartitem_unique_product_in_cart"),
        ("orders", "0009_alter_order_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="cart",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="cart.cart",
            ),
            preserve_default=False,
        ),
    ]
