# Generated by Django 5.2.15 on 2026-06-06 11:30

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_phone_number_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=11, unique=True, validators=[accounts.models.phone_validator]
            ),
        ),
    ]
