# Generated by Django 5.2.15 on 2026-06-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_vendor",
            field=models.BooleanField(default=False),
        ),
    ]
