# Generated by Django 5.2.15 on 2026-06-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_is_vendor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_vendor",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
