# Generated by Django 5.2.15 on 2026-06-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_is_vendor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="", help_text="username", max_length=150, unique=True
            ),
        ),
    ]
