# Generated by Django 5.2.15 on 2026-07-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(help_text="username", max_length=150, unique=True),
        ),
    ]
