# Generated by Django 5.2.15 on 2026-07-07 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=15)),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("expiration_date", models.DateTimeField()),
                ("max_global_usage", models.PositiveIntegerField(default=1)),
                ("current_usages", models.PositiveIntegerField(default=0)),
                ("max_usage_per_user", models.PositiveIntegerField(default=1)),
                ("is_general", models.BooleanField(default=False)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_assignments",
                        to="coupons.coupon",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_coupons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
