# Generated by Django 5.2.15 on 2026-06-06 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_coupon"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="max_limit",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="payments.paymentmethod",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="orders.order",
            ),
        ),
    ]
