# Generated by Django 5.2.15 on 2026-07-04 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_coupon_max_limit_alter_payment_method_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=15)),
                ("description", models.TextField()),
                ("merchent_id", models.TextField()),
                ("authority", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="payment",
            name="transaction",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="payments.transaction",
            ),
            preserve_default=False,
        ),
    ]
