# Generated by Django 5.2.15 on 2026-07-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_transaction_payment_transaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="max_limit",
        ),
        migrations.AddField(
            model_name="coupon",
            name="current_usages",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="coupon",
            name="is_general",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="coupon",
            name="max_global_usage",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="coupon",
            name="max_usage_per_user",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="discount_percent",
            field=models.SmallIntegerField(),
        ),
    ]
