# Generated by Django 5.2.15 on 2026-07-04 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_usercoupon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usercoupon",
            name="usages_count",
        ),
    ]
