# Generated by Django 5.2.15 on 2026-07-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_remove_usercoupon_usages_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="discount_percent",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
