# Generated by Django 5.2.15 on 2026-07-07 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_order_coupon"),
        ("payments", "0007_alter_coupon_discount_percent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usercoupon",
            name="coupon",
        ),
        migrations.RemoveField(
            model_name="usercoupon",
            name="user",
        ),
        migrations.DeleteModel(
            name="Coupon",
        ),
        migrations.DeleteModel(
            name="UserCoupon",
        ),
    ]
