# Generated by Django 5.2.15 on 2026-07-07 11:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_remove_usercoupon_coupon_remove_usercoupon_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="method",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="merchent_id",
        ),
        migrations.AddField(
            model_name="transaction",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="transaction",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="payments.transaction",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="authority",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name="PaymentMethod",
        ),
    ]
