# Generated by Django 5.2.15 on 2026-07-07 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0009_remove_payment_method_remove_transaction_merchent_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="email",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="phone_number",
        ),
    ]
