# Generated by Django 5.2.15 on 2026-07-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_remove_payment_amount_remove_transaction_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
