# Generated by Django 5.2.15 on 2026-07-08 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0011_alter_transaction_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="status",
        ),
    ]
