# Generated by Django 5.2.15 on 2026-07-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0012_remove_transaction_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
