# Generated by Django 5.2.15 on 2026-06-10 08:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_comments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comments",
            new_name="Comment",
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name_plural": "Comments"},
        ),
    ]
